const SIZE={
    HEIGHT_ADMIN_BUTTON:"50px",
    HEIGHT_TABLE_BUTTON:"30px",
    WIDTH_TABLE_BUTTON:"150px",
    WIDTH_ROUNDED_TABLE_BUTTON:"210px",
    HEIGHT_ROUNDED_TABLE_BUTTON:"30px",
    HEIGT_CARD:"70px",
    WIDTH_CARD:"302px",
    BORDER_RADIUS_CARD:"40px"
}
export default SIZE
